import Header from "@/components/header/Header";
import "./globals.css";
import { Inter } from "next/font/google";
import Contact from "@/components/contact/Contact";
import styles from './page.module.css'
import Footer from "@/components/footer/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className={styles.header}><Header /></div>
        {children}
        <Contact />
        <Footer />
      </body>
    </html>
  );
}
